### ISSUE TITLE
ValueError: Invalid choice of solver: ipopt

### ISSUE THREAD

**Issue by Geonhee-LEE** [marinahmurillo/articulated_tractor_trailer_paper#3]
Hi, thanks for your amazing code.

I recently encountered the problem like following: 

```
[INFO] [1697590198.428956, 0.000000]: This node will publish base_link__front_cradle_joint position.
Traceback (most recent call last):
  File "/home/syscib/catkin_ws/src/articulated_tractor_trailer_paper/articulated_tractor_trailer_trajectory/src/articulated_tractor_trajectory.py", line 266, in <module>
    start()
  File "/home/syscib/catkin_ws/src/articulated_tractor_trailer_paper/articulated_tractor_trailer_trajectory/src/articulated_tractor_trajectory.py", line 136, in start
    (controller, Nt, Delta) = export_articulated_tractor_model()
  File "/home/syscib/catkin_ws/src/articulated_tractor_trailer_paper/articulated_tractor_trailer_trajectory/src/export_articulated_tractor_model.py", line 115, in export_articulated_tractor_model
    controller = mpc.nmpc(f=ode_casadi,N=Nnonlin,Delta=Delta,guess=guess,**commonargs)
  File "/home/syscib/.local/lib/python3.6/site-packages/mpctools/tools.py", line 259, in nmpc
    return __optimalControlProblem(*args, **kwargs)
  File "/home/syscib/.local/lib/python3.6/site-packages/mpctools/tools.py", line 644, in __optimalControlProblem
    solver = solvers.ControlSolver(*args, **kwargs)
  File "/home/syscib/.local/lib/python3.6/site-packages/mpctools/solvers.py", line 252, in __init__
    self.initialize(casadioptions, solveroptions)        
  File "/home/syscib/.local/lib/python3.6/site-packages/mpctools/solvers.py", line 329, in initialize
    raise ValueError("Invalid choice of solver: %s" % self.solver)
ValueError: Invalid choice of solver: ipopt
```

I installed the `mpctools` python module which is `2.4.2` and the `casadi` python module version with `3.6.3` version. I also didn't install hsl library. 

Regards

**Comment by Geonhee-LEE** [comment]
![image](https://github.com/marinahmurillo/articulated_tractor_trailer_paper/assets/12562147/9b138aad-38ae-4187-bda4-ff9cd8c56e12)

**Comment by Geonhee-LEE** [comment]
![image](https://github.com/marinahmurillo/articulated_tractor_trailer_paper/assets/12562147/728bf770-309b-419b-9276-ed820e0852d1)
